Python 3.9
firedrakeproject/firedrake pull request #1948
Opened 2021-01-13 15:46 UTC by JDBetteridge

Update the install script to deal with Python version 3.9

Currently installs VTK 9.0.1 from our wheelhouse: https://github.com/firedrakeproject/VTKPythonPackage/releases

We may also have issues with python-lazy-object-proxy, this is unconfirmed.

2021-02-01 20:57 UTC, rckirby commented
I can't run `firedrake-update` while on this branch -- it gives me the "can't install with 3.9" error.

2021-02-03 12:31 UTC, JDBetteridge commented
@rckirby did you tell the Firedrake install script to install this branch or master? If you don't explicitly specify `--package-branch firedrake JDBetteridge/python3.9` the install script will install master and will generate an update script from the master branch. The simplest way (at the moment) to work around this is to delete the check in the `firedake-update` script (L120 `if sys.version_info >= (3, 9): ...`) and run `firedrake-update --no-update-script`. This issue will disappear once the PR is merged.

2021-02-17 16:08 UTC, wence- commented on scripts/firedrake-install
> +if sys.version_info < (3, 6):
Can we catch 3.10 now, rather than "later"

2021-02-17 16:11 UTC, wence- commented on scripts/firedrake-install
> -Please install with Python 3.8 (or with earlier versions).""")
Parameterise by 3.10 not 3.9

2021-02-17 16:12 UTC, wence- commented on scripts/firedrake-install
> +    if sys.version_info >= (3, 9):
==

2021-02-17 16:13 UTC, wence- requested changes
See comments.

2021-02-24 18:03 UTC, wence- approved these changes

2021-02-24 18:03 UTC, merged

2021-02-24 18:04 UTC, wence- commented
@JDBetteridge is the website up to date with supported versions?