Added HDG paper and arXiv preprint to bibliography
firedrakeproject/firedrake pull request #2031
Opened 2021-04-19 16:22 UTC by JDBetteridge

2021-04-19 16:27 UTC, wence- commented
Why does this change _every_ bibtex entry? Did the bibtexparser run change somehow?

2021-04-19 19:32 UTC, wence- commented
@JDBetteridge can you remove all of the whitespace changes?

2021-04-20 09:49 UTC, JDBetteridge commented
Your first comment highlights the issue: Running `firedrake-preprocess-bibtex firedrake-apps.bib` as per https://github.com/firedrakeproject/firedrake/blob/master/docs/source/_static/firedrake-apps.bib is what's adding the additional whitespace.

I was going to edit `firedrake-preprocess-bibtex` to "fix" this, but that isn't the issue, the issue is my inclusion of the line
```
archiveprefix = {arXiv},
```
which has a longer tag than everywhere else in the file. This causes the writer to add an extra space to align the `=` character throughout. I could just remove this tag, then everything goes back to how it was, however this bibtex entry was the automatically generated arXiv bibtex formatted citation that I just copy-pasta'd in.

How would you like me to proceed?:
1. Get rid of this tag, we don't need it, we can just tell everyone to not just copy paste from arXiv (I could add a comment to the top).
2. One off, add a whole bunch more whitespace to this file so that we don't run into this issue every time someone pastes in an automatically generated arXiv bibtex formatted citation (which suffices until someone pastes an even longer tag in there).
3. Something else

2021-04-28 15:41 UTC, dham requested changes

2021-04-28 15:41 UTC, dham commented on docs/source/_static/firedrake-apps.bib
> +  title         = {Code generation for productive portable scalable finite element simulation in Firedrake},
Braces please.

2021-05-05 15:51 UTC, merged