io: change quad facet traversal logic
firedrakeproject/firedrake pull request #2084
Opened 2021-05-19 19:52 UTC by ksagiyam

`plex` quad cell in general can be oriented in 8 different ways relative to the FInAT reference cell, but FInAT quad cell is represented as a tensor product of two intervals, so it is only aware of 2 x 2 = 4 orientations. Thus we need to construct the `cell_closure`, which basically represents the FInAT reference cell, so that `plex` cell would never be mapped to the FInAT cell "wrongly" oriented, and we need to do so in a way that we can recover the correct ordering of the cell DoFs after save/load cycles.

2021-05-20 08:13 UTC, wence- commented
One failure: tests/extrusion/test_variable_layers_numbering.py::test_numbering_quad

That test is checking dof ordering on quads so it is not surprising that it broke.

2021-05-20 09:13 UTC, ksagiyam commented
Thanks! Fixed the order.

2021-05-20 10:36 UTC, wence- requested changes

2021-05-20 10:36 UTC, wence- commented on firedrake/cython/dmcommon.pyx
> +            # cells, and later exchange these values on the halo cells.
These two changed comments seem to be in conflict. The first says:

> We ensure cells in the halo are consistently oriented

The second contradicts this with:

> We only calculate for locally owned and then exchange in the halo.

Which is it?

2021-05-20 12:00 UTC, ksagiyam commented on firedrake/cython/dmcommon.pyx
> +        if cell_cone[0] in (c_facets[off], c_facets[(off + 2) % 4]):
Thanks. Fixed.

2021-05-20 12:17 UTC, wence- commented
Thanks. I guess the only further concern is that this change will break any `DumbCheckpoint` data that users may have lying around on quad meshes.

2021-05-20 12:23 UTC, ksagiyam commented
That is true...

2021-06-04 12:31 UTC, wence- approved these changes

2021-06-04 12:36 UTC, merged

2021-06-04 12:36 UTC, ksagiyam commented
Thanks!