Enable Rank 3
firedrakeproject/firedrake pull request #2088
Opened 2021-05-24 08:21 UTC by jmv2009

Need higher than order two rank tensors.

Just enabling appears to be supported by ufl

2021-05-24 14:34 UTC, wence- requested changes
Thanks, I think we can simplify this a bit further.

2021-05-24 14:34 UTC, wence- commented on firedrake/constant.py
> +        raise RuntimeError("Don't know how to make Constant from data with Tensor rank (order) %d" % rank)
Thanks, I think we can probably support arbitrary rank, so perhaps we can simplify all of this to:

```
if rank = len(shape):
    dat = op2.Global(1, data)
else:
   dat = op2.Global(shape, data)
```

2021-05-24 14:34 UTC, wence- commented on firedrake/constant.py
> +            e = ufl.TensorElement("Real", cell, 0, shape=shape)
And this could just be:
```
else:
   e = ufl.TensorElement("Real", cell, 0, shape=shape)
```

2021-05-25 16:53 UTC, jmv2009 commented
Updated to allow any rank.

2021-05-26 10:39 UTC, wence- commented
> Hmm. Some errors in jenkins... Wonder what they are about.

I think this is not your fault.

2021-06-22 12:21 UTC, wence- approved these changes

2021-06-22 12:21 UTC, merged

2021-06-22 12:21 UTC, wence- commented
Thanks, sorry for the delay.