Add CITATION.cff
firedrakeproject/firedrake pull request #2190
Opened 2021-08-20 09:54 UTC by IvanYashchuk

I don't know if you'd like to use this feature or not, but GitHub has recently added "Cite this repository" button. For more details see https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files.

This PR adds a `CITATION.cff` file. When present in the repository GitHub adds the "Cite this repository" button with generated APA and BibTeX citations.
![image](https://user-images.githubusercontent.com/19621411/130213869-138ef816-25bf-44ec-b424-018919719792.png)

Clicking "View citation file" opens the` CITATION.cff` file.
GitHub uses https://github.com/citation-file-format/ruby-cff to generate the APA and BibTeX. Here is the output:
```
Rathgeber, F., Ham, D. A., Lawrence, M., Lange, M., Luporini, F., Mcrae, A. T. T., Bercea, G., Markall, G. R., & Kelly, P. H. J. Firedrake: Automating the Finite Element Method by Composing Abstractions. ACM Trans. Math. Softw., 43(3), 1. https://doi.org/10.1145/2998441
```
```
@article{Rathgeber_Firedrake_Automating_the,
author = {Rathgeber, Florian and Ham, David A. and Lawrence, Mitchell and Lange, Michael and Luporini, Fabio and Mcrae, Andrew T. T. and Bercea, Gheorghe-Teodor and Markall, Graham R. and Kelly, Paul H. J.},
doi = {10.1145/2998441},
journal = {ACM Trans. Math. Softw.},
number = {3},
pages = {1--27},
title = {{Firedrake: Automating the Finite Element Method by Composing Abstractions}},
url = {http://arxiv.org/abs/1501.01809},
volume = {43}}
```
Unfortunately, it's not possible to change the reference tag of the generated BibTeX to match https://github.com/firedrakeproject/firedrake/blob/c0912a406323e742466cb77500abc8e15c4287f5/docs/source/_static/bibliography.bib#L281

"message" from CITATION.cff seems not to be used currently by GitHub, maybe this will change in the future, but still, I added a link to the citation webpage of Firedrake.

2021-08-20 18:56 UTC, bueler commented
If you don't like the citation generated by the `.cff` then you can always just add the `.bib`.  I did this for my book because I want users of the software (= examples from the book) to cite the book not the examples repo.  But fiddling with the `.cff` `preferred-citation` mechanism did not yield a reasonable book citation.  So I reverted to adding a raw `CITATION.bib`.  Github recognizes that, adds a "cite this repo" link, and then hands the user the raw `CITATION.bib`.  Not ideal, but at least I fully control the citation.  See the result at https://github.com/bueler/p4pdes

2021-09-09 15:41 UTC, dham requested changes
The message part of this seems right. I am nervous about providing the citation, because I am worried that  readers will just jump to just cite this.

2021-11-04 19:22 UTC, arfon commented
Note, GitHub now supports a range of different `preferred-citation` types: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files#citing-something-other-than-software

2021-11-04 19:35 UTC, IvanYashchuk commented
Hey @arfon! Thanks for chiming in. Having different `preferred-citation` types supported is great but the `message` field from `CITATION.cff` is still not used by GitHub. For this project, it would be greatly beneficial to guide readers to the website with instructions on citing different components of the software.
```
message: |
    "If you publish results using Firedrake, we would be grateful if you would cite it using the following metadata.
    Please visit https://www.firedrakeproject.org/citing.html for extended instructions."
```
It would be great to be able to customize the default "If you use this software in your work, please cite it using the following metadata." message after clicking the "Cite this repository" button.

2021-11-04 19:37 UTC, arfon commented
Ah right. Yes I'm afraid the message can't be changed at this point sorry.

2021-11-05 11:56 UTC, wence- commented
My conclusion is that the automatic citation mechanism offered by `CITATION.cff` isn't currently suitable for Firedrake. The set of papers that one should cite for a given simulation depends on the particular configuration of the simulation (and Firedrake/PETSc's runtime `-citations` flag attempts to tell you these).

TBH: I think this is going to be generically true for any large piece of research software (especially those with dependencies), best practice will be to cite multiple papers dependent on the exact composition of algorithms employed. I don't think that a static file can capture this information (which is why the instructions for citing Firedrake basically say "we determine it for you at runtime").

I'm therefore inclined to close this. I think on the repository, the right thing would be for the "cite this repository" button to allow us just to drop arbitrary text with a link to somewhere, rather than trying to provide a static citation.

2021-11-07 19:12 UTC, arfon commented
> I'm therefore inclined to close this. I think on the repository, the right thing would be for the "cite this repository" button to allow us just to drop arbitrary text with a link to somewhere, rather than trying to provide a static citation.

Sounds reasonable. Please note, any of the [files listed here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files#other-citation-files) will generate the citation prompt in the GitHub UI (you can then have whatever you want written in the linked file).

2021-11-08 17:41 UTC, wence- commented
@IvanYashchuk do you want to have a go at that last suggestion instead of `citations.cff`? That is, right `CITATION.md` that just points at the relevant firedrake webpage. Do we think that is something we want?

2021-11-08 18:49 UTC, IvanYashchuk commented
Yes, I could replace `CITATION.cff` with `CITATION.md` that simply points to the webpage. I'll open a new PR for that and close this one.

2021-11-08 18:49 UTC, closed without merging