improve BLAS threads checking
firedrakeproject/firedrake pull request #2205
Opened 2021-09-02 15:21 UTC by danshapero

The current code in __init__.py checks for the presence of OpenBLAS and sets the number of threads to 1 in order to prevent awful performance regressions. This does the right thing in some setups but not others:

1. You have regular old Netlib BLAS.
2. You're linking to the Intel MKL library for BLAS.
3. You installed OpenBLAS via the `--with-blas=download` option when building PETSc.

You still get the warning even in the last case because the current code uses `find_library` to look for OpenBLAS, which only looks in places like `/usr/lib/`, and not in the PETSc build tree. This patch handles the other cases as well by parsing the output of either `ldd` or `otool` (platform depending) on `firedrake.petsc.PETSc.__file__`.

I've tested it on my Mac and in Docker images with Netlib BLAS, Intel MKL, OpenBLAS installed via apt-get, and OpenBLAS installed via PETSc.

2021-09-02 15:52 UTC, dham requested changes

2021-09-02 15:52 UTC, dham commented on firedrake/petsc.py
> +    entry = next((e for e in entries if "blas" in e or "libmkl" in e), None)
Less magic please!

2021-09-02 16:26 UTC, danshapero commented
[dockerfiles.zip](https://github.com/firedrakeproject/firedrake/files/7100344/dockerfiles.zip)

Here are the dockerfiles I used to test with Netlib BLAS and MKL.

2021-09-02 22:06 UTC, danshapero commented on firedrake/petsc.py
> +    entry = next((e for e in entries if "blas" in e or "libmkl" in e), None)
Magic expunged!

2021-09-02 22:23 UTC, wence- approved these changes
Looks good!

2021-09-03 08:59 UTC, merged

2021-09-03 09:00 UTC, wence- commented
Thanks!