Changes for Python 3.11
firedrakeproject/firedrake pull request #2358
Opened 2022-02-18 18:35 UTC by JDBetteridge

2022-02-21 14:17 UTC, connorjward requested changes
I think you need to include these changes on the [website](https://firedrakeproject.org/download.html#system-requirements) too. Also maybe look at https://github.com/firedrakeproject/firedrake/pull/2339 where I've done something similar but hopefully in a way that is easier to update.

2022-12-15 10:13 UTC, ReubenHill approved these changes
I have tested this on my intel mac with python 3.11 and python 3.10 and it works fine.

2022-12-15 10:16 UTC, connorjward approved these changes

2022-12-15 10:16 UTC, merged

2022-12-15 11:09 UTC, JDBetteridge commented
:tada: :tada: :taco: