Compatibility with macOS 12.3
firedrakeproject/firedrake pull request #2385
Opened 2022-03-19 12:30 UTC by bourdin

- Added the option to use external MI (--honour-mpi-dir_) since I can't get petsc to compile mpich at the moment and brew mpich works file
   - Have hwloc installed by homebrew for the same reason

At the moment, installing on macOS 12.3 on a M1 system only works when --honour-mpi-dir is passed (and MPI_DIR is set to $HOMEBREW_PREFIX, for instance). Doing so also speeds up building tremendously.

2022-03-19 13:08 UTC, wence- commented
Does it not work to just set --mpicc etc to the mpi compilers provided by homebrew? This has always worked for me on pre-M1 systems.

It also looks like there are a bunch of changes that are unrelated to this new option, is that deliberate?

2022-03-19 13:28 UTC, bourdin commented
I had troubles with some packages using Monica as the c compiler. I can try again tu use —with-mpicc
The other changes are deliberate: for some reason, setting MACOSX_SOMETHING leads to a working build but examples fail to compile. 
hwloc does not build with the version of PETSc that you are using
H5py seemed to always try to use mpicc built by PETSc

2022-05-03 04:27 UTC, dham requested changes
I have no objection to allowing --honour-mpi-dir, however it looks like there is also a lot else going on here and I don't understand why the additional changes are desirable.

2022-05-03 04:27 UTC, dham commented on scripts/firedrake-install
> +        # As of 2022-03-17, it looks like setting MACOSX_DEPLOYMENT_TARGET on macOS 12.3 system actually breaks petsc configuration
This has now been fixed in a hopefully better way in #2408. I claim we don't want to delete this code.

2022-05-03 04:27 UTC, dham commented on scripts/firedrake-install
> -def build_and_install_petsc4py():
It's not clear to me why we want to make this change.

2022-05-03 04:27 UTC, dham commented on scripts/firedrake-install
> -if mode == "install" and args.honour_petsc_dir:
Why is this being deleted?

2022-05-03 04:27 UTC, dham commented on scripts/firedrake-install
> -def get_petsc_packages(minimal=False):
Why is this being deleted?

2023-06-21 08:36 UTC, dham commented
Seems no longer required.

2023-06-21 08:36 UTC, closed without merging