Load binary gmsh file
firedrakeproject/firedrake pull request #2414
Opened 2022-04-16 09:59 UTC by lrtfm

2022-05-03 01:36 UTC, dham requested changes
This looks good and thanks for the contribution. However, we need a very basic test just so we know if this stops working.

What needs to happen is:

1. Add a binary `.msh` file to `tests/meshes`. A binary version of one of the files that is in there would be fine.
2. add a test file, say, `tests/regression/test_load_mesh.py` containing a test that loads the mesh and does something really basic. For example you could integrate 1 over the mesh and check that it gets the expected value.

2022-05-03 01:37 UTC, dham requested changes
Oh, and you need to pass flake8 ;)

2022-08-06 04:45 UTC, lrtfm commented
@dham I think the problems have been resolved. Can this be merged?

2022-08-08 02:13 UTC, dham submitted a review, later dismissed

2022-08-08 04:23 UTC, dham approved these changes

2022-08-08 04:23 UTC, merged