Add destroy() to custom PCs
firedrakeproject/firedrake pull request #2567
Opened 2022-09-29 15:14 UTC by pbrubeck

Python PCs should destroy internal PETSc objects when `destroy()` is called on them, which we weren't doing before.

2022-09-29 15:24 UTC, JDBetteridge requested changes
Thanks for fixing this! I think we need to move the logic for these `.destroy()` calls to the base class. This will remove repetition and make sure any new `PC`s also clean up after themselves.

2022-09-29 15:24 UTC, JDBetteridge commented on firedrake/preconditioners/pcd.py
> +    def destroy(self, pc):
This method could then override the base class method

2022-09-29 15:50 UTC, pbrubeck commented on firedrake/preconditioners/assembled.py
> +
If we want to generalize this to the base class, we would have to iterate through all attributes of the PC, and call destroy on them if they are a PETSc object. Do you think this is the way to go?

2022-09-29 15:53 UTC, pbrubeck commented on firedrake/preconditioners/assembled.py
> +
Something like this
```
import operator
for a in dir(self):
     sub = operator.attrgetter(a)(self)
     if isinstance(sub, (PETSc.KSP, PETSc.PC, PETSc.Mat, PETSc.Vec, PETSc.IS)):
        sub.destroy()
```

2022-09-29 15:59 UTC, JDBetteridge commented on firedrake/preconditioners/assembled.py
> +
Oh, I see what you mean. In theory these should be garbage collected by Python if their reference count goes to zero.

Finding what is holding on to a reference can be quite challenging if this memory isn't being freed up.

2022-10-06 11:02 UTC, JDBetteridge approved these changes

2022-10-06 11:02 UTC, merged