[WIP] Netgen Integration
firedrakeproject/firedrake pull request #2607
Opened 2022-10-28 11:47 UTC by UZerbinati

2022-11-09 16:54 UTC, dham requested changes
This is lovely and very nearly good to go. Can we please just have one of the tests set to run in parallel just to ensure that that works (and stays working).

2022-11-09 18:02 UTC, UZerbinati commented
Sorry,it turns out that making it work in parallel is more complicated then expected :( This comes from the fact that NetGen already stores the Mesh in parallel. I exposed the `DMPlexBuildFromCellListParallel` method in petsc4py ([https://gitlab.com/UZerbinati1/petsc](url) the fork) to try solving this issue, but I'm having some trouble using it (on going discussion in the Slack).

2022-12-14 16:29 UTC, dham commented on tests/regression/test_netgen.py
> +    def Refine(msh, marked):
make this a mesh method. Have `marked` be a DG0 field over the mesh which is 0 or 1.

2022-12-14 16:33 UTC, dham commented on tests/regression/test_netgen.py
> +        with eta.dat.vec as etaVec:
It would be much nicer to do this in Firedrake.

2023-01-18 16:18 UTC, UZerbinati commented on firedrake/mesh.py
> +            surfMesh, dim = False, 3
write dim as tdim

2023-01-18 16:20 UTC, UZerbinati commented on firedrake/mesh.py
> +                    plex.setLabelValue(dmcommon.FACE_SETS_LABEL, join[0], int(e.surfaces[1]))
EDGE_SETS_LABEL not FACE_SETS_LABEL

2023-01-18 16:22 UTC, UZerbinati commented on firedrake/mesh.py
> +                for e in ngmesh.Elements2D():
Add python comment on why this should not give performance problem

2023-01-18 16:30 UTC, UZerbinati commented on firedrake/mesh.py
> +        setattr(MeshGeometry, "Refine", Refine)
Check if `setattr` is needed.

2023-01-18 16:31 UTC, UZerbinati commented on firedrake/mesh.py
> +                    self.netgen_mesh.RefineFlaged(0, True)
Correct spelling

2023-01-18 16:36 UTC, UZerbinati commented on scripts/firedrake-install
> +        git_clone("git+https://github.com/firedrakeproject/firedrake.git@uzerbinati/netgen-integration")
No need

2023-01-18 16:39 UTC, UZerbinati commented on scripts/firedrake-install
> +    log.info("Depending on your platform, NetGen may take an hour or more to build!")
Add optional dep on netgen setup.py. Add flag to install netgen with OCC.

2023-01-18 16:41 UTC, UZerbinati commented on tests/regression/test_netgen.py
> +
Easier test. Integrating function on netgen mesh of square, cube and sphere.

2023-01-18 16:43 UTC, UZerbinati commented on tests/regression/test_netgen.py
> +from netgen.occ import *
not import all, choose what to import

2023-04-05 15:37 UTC, JDBetteridge commented on tests/regression/test_netgen.py
> +    comm = MPI.COMM_WORLD
COMM_WORLD is already in the firedrake namespace (you get it from from firedrake import *)

2023-04-05 15:38 UTC, JDBetteridge commented on tests/regression/test_netgen.py
> +from mpi4py import MPI
See comment below, this import can be removed

2023-04-19 15:21 UTC, dham commented on scripts/firedrake-install
> +                        help="Install Netgen as well.")
```suggestion
                        help="Install Netgen.")
```

2023-04-19 15:22 UTC, dham submitted a review, later dismissed

2023-04-19 15:24 UTC, dham commented on scripts/firedrake-install
> +                        help="Install Netgen as well.")
```suggestion
                        help="Install Netgen.")
```

2023-04-19 15:25 UTC, dham approved these changes

2023-04-25 20:02 UTC, merged