Ksagiyam/io do not use pickle
firedrakeproject/firedrake pull request #2787
Opened 2023-02-24 11:25 UTC by ksagiyam

Use `repr` instead of pickling.

This involved a minor fix in UFL, so this PR depends on

2023-03-08 16:55 UTC, dham commented on firedrake/bcs.py
> +            except BaseException:
`ValueError`

2023-03-08 17:05 UTC, dham requested changes
minor quibble.

2023-03-09 13:28 UTC, ksagiyam commented on firedrake/bcs.py
> +            except BaseException:
Fixed.

2023-03-13 16:42 UTC, merged

2023-03-13 16:43 UTC, ksagiyam commented
Merged as discussed.