Extend facet marking to 1D meshes
firedrakeproject/firedrake pull request #2802
Opened 2023-03-07 17:39 UTC by francesco-ballarin

After discussion with @ksagiyam. Please double check, the test passes but I am not fully sure of what I am doing ;)

2023-03-07 18:13 UTC, ksagiyam requested changes
Thanks! I requested some minor changes, but otherwise looks good to me.

2023-03-07 18:13 UTC, ksagiyam commented on firedrake/mesh.py
> +        ):
Lint will fail, so we want something like:
```
        elif self.cell_dimension() == 1 and elem.family() == "Lagrange" and elem.degree() == 1 or \
                self.cell_dimension() > 1 and elem.family() == "HDiv Trace" and elem.degree() == 0:
```

2023-03-07 18:13 UTC, ksagiyam commented on tests/regression/test_mark_entities.py
> +
Want double blank lines.

2023-03-07 18:15 UTC, ksagiyam commented on firedrake/mesh.py
> +        ):
and similar change in `RelabeledMesh`.

2023-03-08 19:58 UTC, francesco-ballarin commented
Not sure why it still says "changes requested", I believe I addressed all of them...

2023-03-09 08:24 UTC, wence- commented
> Not sure why it still says "changes requested", I believe I addressed all of them...

@ksagiyam has to agree that you addressed them as requester :)

2023-03-09 10:04 UTC, ksagiyam approved these changes

2023-03-09 10:05 UTC, ksagiyam commented
Done!

2023-03-09 13:24 UTC, merged

2023-03-10 10:07 UTC, francesco-ballarin commented
Thanks @ksagiyam!