Fix Constant numbering
firedrakeproject/firedrake pull request #3011
Opened 2023-06-29 13:41 UTC by connorjward

Fixes https://github.com/firedrakeproject/firedrake/issues/2999.

Requires https://github.com/FEniCS/ufl/pull/178 (and for our fork to be updated).

I think that wider problems exist regarding our implementation of `Constant` (see [next week's meeting](https://github.com/firedrakeproject/firedrake/wiki/Firedrake-meeting-2023-07-05#cw-codegen-issues-with-the-new-constant)), but this will resolve the performance problems.

2023-06-30 08:44 UTC, connorjward commented on .github/workflows/build.yml
> +            --package-branch ufl connorjward/counted-mixin2 \
```suggestion
            --package-branch ufl connorjward/counted-mixin \
```

2023-08-11 11:21 UTC, JDBetteridge requested changes
I think this is good to go once our UFL branch is moved forwards

2023-08-11 11:21 UTC, JDBetteridge commented on .github/workflows/build.yml
> +            --package-branch ufl connorjward/test-upstream \
Drop before merge

2023-08-11 13:39 UTC, connorjward commented on .github/workflows/build.yml
> +            --package-branch ufl connorjward/test-upstream \
```suggestion
```

2023-08-11 13:51 UTC, merged