Delegate checkpoint only if the meshes are equal
firedrakeproject/firedrake pull request #3016
Opened 2023-07-10 10:20 UTC by Ig-dolci

---
name: "Bug fix"

---

# Description
Delegate checkpoint only if the meshes are equal

## Fixes Issues:
- Make a list of issues (with links!)
- [Like this Issue#3009](https://github.com/firedrakeproject/firedrake/issues/3009)

If issues are fixed by this PR, prepend each of them with the word
"fixes", so they are automatically closed when this PR is merged. For
example "fixes #123, fixes #456".

# Checklist for author:

- [ ] I have linted the codebase (`make lint` in the `firedrake` source directory).
- [ ] My changes generate no new warnings.
- [ ] All of my functions and classes have appropriate docstrings.
- [ ] I have commented my code where its purpose may be unclear.
- [ ] I have included and updated any relevant documentation.
- [ ] Documentation builds locally (`make linkcheck; make html; make latexpdf` in `firedrake/docs` directory)
- [ ] I have added tests specific to the issues fixed in this PR.
- [ ] I have added tests that exercise the new functionality I have introduced
- [ ] Tests pass locally (`pytest tests` in the `firedrake` source directory) (useful, but not essential if you don't have suitable hardware).
- [ ] I have performed a self-review of my own code using the below guidelines.

# Checklist for reviewer:

- [ ] Docstrings present
- [ ] New tests present
- [ ] Code correctly commented
- [ ] No bad "code smells"
- [ ] No issues in parallel
- [ ] No CI issues (excessive parallelism/memory usage/time/warnings generated)
- [ ] Upstream/dependent branches and PRs are ready

Feel free to add reviewers if you know there is someone who is already aware of this work.

Please open this PR initially as a draft and mark as ready for review once CI tests are passing.

2023-07-10 10:29 UTC, dham requested changes
Please also add a test which checks for the behaviour reported in #3009 .

2023-07-10 10:29 UTC, dham commented on firedrake/adjoint/function.py
> +                    if other_mesh == self_mesh:
```suggestion
                    if other.function_space().mesh() == self.function_space().mesh():
```
Don't introduce unnecessary variables.

2023-07-10 10:37 UTC, Ig-dolci commented
> Please also add a test which checks for the behaviour reported in #3009 .

Should I add in pyadjoint/tests/firedrake_adjoint or firedrake/tests?

2023-07-11 07:33 UTC, Ig-dolci commented
I observed the test errors with tests/regression/test_netgen.py also in the master branch. Do you know if these errors are expected?

2023-07-13 16:23 UTC, closed without merging