Copy slec4py to install
firedrakeproject/firedrake pull request #3037
Opened 2023-07-25 13:30 UTC by JDBetteridge

# Description
Make `build_and_install_petsc4py()` install script function generic to handle slepc4py.

## Associated Pull Requests:
- N/A

## Fixes Issues:
- Fixes #3033 

# Checklist for author:

- [ ] I have linted the codebase (`make lint` in the `firedrake` source directory).
- [ ] My changes generate no new warnings.
- [ ] All of my functions and classes have appropriate docstrings.
- [ ] I have commented my code where its purpose may be unclear.
- [ ] I have included and updated any relevant documentation.
- [ ] Documentation builds locally (`make linkcheck; make html; make latexpdf` in `firedrake/docs` directory)
- [ ] I have added tests specific to the issues fixed in this PR.
- [ ] I have added tests that exercise the new functionality I have introduced
- [ ] Tests pass locally (`pytest tests` in the `firedrake` source directory) (useful, but not essential if you don't have suitable hardware).
- [ ] I have performed a self-review of my own code using the below guidelines.

# Checklist for reviewer:

- [ ] Docstrings present
- [ ] New tests present
- [ ] Code correctly commented
- [ ] No bad "code smells"
- [ ] No issues in parallel
- [ ] No CI issues (excessive parallelism/memory usage/time/warnings generated)
- [ ] Upstream/dependent branches and PRs are ready

2023-07-25 13:52 UTC, JDBetteridge commented
Tested working on the Pileus workstation

2023-07-26 13:01 UTC, dham requested changes
Too clever.

2023-07-26 13:01 UTC, dham commented on scripts/firedrake-install
> +        get_x4py_dir = get_slepc4py_dir
```suggestion
def build_and_install_x4py(package="petsc4py"):
    if package == "petsc4py":
        x4py_dir = get_petsc4py_dir()
    elif package == "slepc4py":
        x4py_dir = get_slepc4py_dir()
```

2023-07-26 13:01 UTC, dham commented on scripts/firedrake-install
> +                shutil.copytree(get_x4py_dir(), x4py_copy, dirs_exist_ok=True)
```suggestion
                shutil.copytree(x4py_dir, x4py_copy, dirs_exist_ok=True)
```

2023-07-26 13:01 UTC, dham commented on scripts/firedrake-install
> +            pipargs = ["-vvv", "--ignore-installed", get_x4py_dir()]
```suggestion
            pipargs = ["-vvv", "--ignore-installed", x4py_dir]
```

2023-07-26 13:24 UTC, dham approved these changes

2023-07-26 16:09 UTC, merged