Ensure transpose interpolation gives correct answer
firedrakeproject/firedrake pull request #3167
Opened 2023-10-17 13:53 UTC by ReubenHill

I think we need to ensure that the output covector coefficients are zeroed before we do our multTranspose operation in case our interpolation matrix is non-square (e.g. going from a vertex-only mesh to its input ordering where not all points in the input ordering are in the vertex-only mesh).

Certainly where we are using a reduce operation for vertex-only mesh to input ordering, this is what we need to do.

I welcome mathematical refutations!

2023-10-18 14:08 UTC, ReubenHill commented on firedrake/interpolation.py
> +                result = output or firedrake.Function(V)
This should be a `Cofunction` but it's not enforced anywhere else in interpolation...

2023-10-18 14:08 UTC, ReubenHill commented on firedrake/interpolation.py
> +                result.zero()
`Cofunction` has no `zero()` method

2024-01-08 12:27 UTC, wence- commented on firedrake/interpolation.py
> +            target_vec.getArray()[:] = 0.0
`target_vec.zero()` makes this future-proof against GPU usage.

2024-01-10 16:18 UTC, dham commented on firedrake/interpolation.py
> +            target_vec.getArray()[:] = 0.0
```suggestion
            target_vec.zero()
```

2024-01-10 16:19 UTC, dham approved these changes

2024-02-14 16:50 UTC, dham requested changes
The test fails are caused by this line, so this is clearly not right.

2024-03-22 16:36 UTC, ReubenHill commented
> The test fails are caused by this line, so this is clearly not right.

Looks like it worked before switching to an architecture agnostic approach. I wonder what's different?

2024-03-22 16:42 UTC, ksagiyam commented on firedrake/interpolation.py
> +            target_vec.zero()
```suggestion
            target_vec.zeroEntries()
```

2024-10-10 12:43 UTC, JDBetteridge approved these changes
Approved in meeting

2024-10-10 12:43 UTC, merged