Emmarothwell1/restricted _function_space: Implement a RestrictedFunctionSpace class.
firedrakeproject/firedrake pull request #3215
Opened 2023-11-09 16:07 UTC by emmarothwell1

# Implement a RestrictedFunctionSpace class.
(Part of an M4R project)
This inherits from FunctionSpace, with the main difference being how boundary conditions are treated.  
This will hopefully be used in cases where users have boundary conditions they want to apply.

2023-12-11 13:38 UTC, ksagiyam commented on firedrake/functionspaceimpl.py
> +        self._shared_data = sdata = get_shared_data(function_space._mesh, function_space.ufl_element(), self.boundary_set)
`super().__init__()` sets `self.node_set` etc. using `shared_data` of the parent function space (so, in your current example, `V_res.node_set is V.node_set`).
We should probably define `_init_with_shared_data` method and do something like:
```
class FunctionSpace(...):
    sdata = get_shared_data(mesh, elem)
    self._init_with_shared_data(mesh, elem, name, sdata)

class RestrictedFunctionSpace(...):
    boundary_set = ...
    sdata = get_shared_data(mesh, elem, boundary_set=boundary_set)
    self._init_with_shared_data(mesh, elem, name, sdata)
```

2023-12-11 13:44 UTC, ksagiyam commented
In serial `lgmap` is not aware of the changes you have made in `dmcommon.make_global_numbering`:
https://github.com/OP2/PyOP2/blob/d017d594e0bda694a71c4180fbfeae1cba473e93/pyop2/types/dataset.py#L122.
I think we can just delete `self.comm.size == 1` case.

2023-12-11 14:32 UTC, ksagiyam commented on firedrake/functionspacedata.py
> +        key = (nodes_per_entity, real_tensorproduct, boundary_set)
`self.map_cache` must also be keyed by `boundary_set`.

2023-12-12 16:34 UTC, ksagiyam commented
With the above changes, I was able to get a 4 x 4 matrix with nonzeros only on the top-left 2 x 2 submatrix; this indicates that your lgmap is correct. The problem now reduces to getting a matrix of the right shape.
The allocation of a matrix is done in `assemble.py` using `op2.Sparsity`. The actual assembly is done in the same file using `op2.Parloop`.
When allocating, the size of the matrix is set here [https://github.com/OP2/PyOP2/blob/d017d594e0bda694a71c4180fbfeae1cba473e93/pyop2/sparsity.pyx#L140](https://github.com/OP2/PyOP2/blob/d017d594e0bda694a71c4180fbfeae1cba473e93/pyop2/sparsity.pyx#L136), where `rset.size` is `rset.set.size`, which is the size of `core + owned` DoFs of the given rank. Here, `rset.set` is `V.node_set`. As we now want the size of the reduced matrix here, we probably want `V.node_set` to store the size of the "constrained owned DoFs" as, say, `V.node_set.constrained_size`, when we make `node_set` here https://github.com/firedrakeproject/firedrake/blob/9c50131b511845db99542a7f6e1bebcbf14bcd73/firedrake/functionspacedata.py#L107.
The computation of the size of the "constrained owned DoFs" should probably be done when we compute renumbering to push "constrained owned DoFs" to the end of `core + owned` block.

We currently only renumber (reorder) entities so that a local vector sees core, owned, and ghost DoFs in this order; we compute renumbering using `dmcommon.plex_renumbering` https://github.com/firedrakeproject/firedrake/blob/8d97a0741907a54cfea1aa48a1ec4903f11756b3/firedrake/cython/dmcommon.pyx#L2265 when we construct a mesh, and set that to a section at https://github.com/firedrakeproject/firedrake/blob/8d97a0741907a54cfea1aa48a1ec4903f11756b3/firedrake/cython/dmcommon.pyx#L1231C41-L1231C41 so that `PetscSectionGetOffset()` would return offsets in the local vector as we want. 
As we now want to push "constrained owned DoFs" to the end of the `core + owned` block,
when `dmcommon.create_section` is called with `boundary_set`, we need to compute renumbering using `dmcommon.plex_renumbering` (with additional argument `boundary_set`) instead of using the one stored in the mesh. When we do this, we can also compute the size of the constrained owned DoFs.

2023-12-12 21:40 UTC, ksagiyam commented
You should also push your PyOP2 branch and do something exactly like this https://github.com/firedrakeproject/firedrake/pull/3288/files for CI to pick up your PyOP2 branch.

2023-12-13 17:25 UTC, ksagiyam commented
Some PRs that will conflict with yours have just been merged, so you will need to rebase when you have time. Specifically, there has been a change in `functionspaceimpl.py`. I think the easiest way to deal with this is to first respect all changes in `functionspaceimpl.py` on `master` and then cherry pick/apply your changes on top of that, or just do it in your favorite way.

2024-01-09 21:11 UTC, ksagiyam requested changes
You need to rebase to make CI running.

As for PyOP2, this PR https://github.com/OP2/PyOP2/pull/714 has made `Mat` and `Sparsity` inherit sizes from `Dataset.layout_vec`, which represents corresponding vectors, so, after rebasing, you should only need to shrink the size of `Dataset.layout_vec`.

You will also need to run `make` in PyOP2, just as you do in Firedrake after changing Cython file. Before running `make` in PyOP2, you will need to:
```
export PETSC_DIR=$VIRTUAL_ENV/src/petsc
export PETSC_ARCH=default
```
.

2024-01-25 22:36 UTC, ksagiyam commented
Cache issue has been sorted out https://github.com/firedrakeproject/firedrake/pull/3355, so rebase.

2024-04-19 23:41 UTC, ksagiyam requested changes

2024-04-19 23:41 UTC, ksagiyam commented on firedrake/functionspaceimpl.py
> +        return node_count*self.value_size
I think we should leave `dof_count()` unchanged, but change `node_count()` as:
```
    @utils.cached_property
    def node_count(self):
        ...
        constrained_node_set = set()
        for sub_domain in self.boundary_set:
            constrained_node_set.update(self._shared_data.boundary_nodes(self, sub_domain))
        return self.node_set.total_size - len(constrained_node_set)
```

2024-04-19 23:41 UTC, ksagiyam commented on firedrake/functionspaceimpl.py
> +            label += str(boundary_domain)
We probably want `_` or something to distinguish '(1, 2)' and '(12, )'.

2024-04-19 23:41 UTC, ksagiyam commented on firedrake/functionspaceimpl.py
> +        self._label = "_".join(str(s._label) for s in spaces)
Probably:
```suggestion
        label = ""
        for s in spaces:
            label += "(" + s._label + ")_"
        self._label = label
```
or anything that is not ambiguous.

2024-04-19 23:41 UTC, ksagiyam commented on tests/regression/test_restricted_function_space.py
> +    original_form = u * v * dx
```suggestion
    original_form = inner(u, v) * dx
```
to make it complex safe. The same change must happen everywhere in the below.

2024-04-19 23:41 UTC, ksagiyam commented on tests/regression/test_restricted_function_space.py
> +    a2 = (dot(sigma2, tau2) + div(tau2)*u2 + div(sigma2)*v2)*dx
```suggestion
    a = (inner(sigma, tau) + inner(u, div(tau)) + inner(div(sigma), v))*dx
    a2 = (inner(sigma2, tau2) + inner(u2, div(tau2)) + inner(div(sigma2), v2))*dx
```
and so on.

2024-04-19 23:42 UTC, ksagiyam commented
Also please run `make lint` and fix lint failures.

2024-04-22 20:29 UTC, ksagiyam requested changes

2024-04-22 20:29 UTC, ksagiyam commented on firedrake/assemble.py
> +            return self._make_dat_global_kernel_arg(el, frozenset(boundary_set))
I think this block should be more like:
```
            for V in Vs:
                if V.ufl_element().family() != "Real":
                    el = create_element(V.ufl_element())
                    boundary_set = V.boundary_set
                    break
```

2024-04-22 21:25 UTC, ksagiyam requested changes

2024-04-22 21:25 UTC, ksagiyam commented on tests/regression/test_restricted_function_space.py
> +                                            bcs=bc_res, bc_shift=100, restrict=False)
```suggestion
    other_eigenproblem = LinearEigenproblem(A=inner(u_res.dx(0), v_res)*dx, M=M_res,
                                            bcs=bc_res, bc_shift=100, restrict=False)
```

2024-04-22 21:25 UTC, ksagiyam commented on tests/regression/test_restricted_function_space.py
> +                                      bc_shift=100, restrict=False)
```suggestion
    eigenproblem = LinearEigenproblem(A=inner(u.dx(0), v)*dx, bcs=bc,
                                      bc_shift=100, restrict=False)
```

2024-04-22 21:25 UTC, ksagiyam commented on tests/regression/test_restricted_function_space.py
> +                                            bc_shift=100, restrict=True)
```suggestion
    other_eigenproblem = LinearEigenproblem(A=inner(u.dx(0), v)*dx, bcs=bc,
                                            bc_shift=100, restrict=True)
```

2024-04-22 21:25 UTC, ksagiyam commented on firedrake/functionspaceimpl.py
> +        return node_count*self.value_size
I meant you wouldn't need to change `dof_count` as long as you changed `node_count` correctly (which has been done):
```
    @utils.cached_property
    def dof_count(self):
        ...
        return self.node_count*self.value_size
```

2024-04-22 22:33 UTC, ksagiyam requested changes

2024-04-22 22:33 UTC, ksagiyam commented on firedrake/assemble.py
> +                                signature=signature)
I think we do not need to pass signature here, as `kernel_args` will distinguish what we want to distinguish. I think the issue we originally had was that `_GlobalKernelBuilder` was cached keyed by `form.signature()`, by `form.signature()` did not correctly label restricted functions, which has been fixed.

2024-04-25 14:30 UTC, emmarothwell1 commented on .github/workflows/build.yml
> +            --package-branch pyop2 emmarothwell1/restricted_function_space \
```suggestion
            --package-branch pyop2 emmarothwell1/restricted_function_space_review \
```

2024-04-25 14:40 UTC, dham commented on firedrake/functionspaceimpl.py
> +    corresponding to V is V0.
Modify this to explain that when solving, test and trial functions are drawn from V0 only, and values of the solution in VΓ are treated as constant.

2024-04-25 14:47 UTC, dham requested changes

2024-04-25 14:47 UTC, dham commented on firedrake/solving.py
> +        options_prefix, restrict = _extract_args(*args, **kwargs)
Need to doculemt the `restrict` argument in the `solve` docstring.

2024-04-25 14:47 UTC, dham commented on firedrake/variational_solver.py
> +            space remains the same.
```suggestion
        :param restrict: (optional) If `True`, use restricted function spaces,
            that exclude Dirichlet boundary condition nodes,  internally for
            the test and trial spaces. 
```

2024-04-25 14:47 UTC, dham commented on firedrake/variational_solver.py
> +                 space remains the same.
```suggestion
        :param restrict: (optional) If `True`, use restricted function spaces,
            that exclude Dirichlet boundary condition nodes,  internally for
            the test and trial spaces. 
```

2024-04-25 14:53 UTC, dham commented on firedrake/variational_solver.py
> +        self.restrict = restrict
```suggestion
        for bc in bcs:
            if isinstance(bc, EquationBC):
                restrict = False
        self.restrict = restrict
```

2024-04-25 14:54 UTC, dham requested changes

2024-04-25 14:54 UTC, dham commented on firedrake/variational_solver.py
> +                 is_linear=False, restrict=False):
```suggestion
                 is_linear=False, restrict=True):
```

2024-04-25 14:54 UTC, dham commented on firedrake/solving.py
> +    restrict = kwargs.get("restrict", False)
```suggestion
    restrict = kwargs.get("restrict", True)
```

2024-04-25 22:16 UTC, ksagiyam approved these changes

2024-04-26 21:34 UTC, ksagiyam commented on .github/workflows/build.yml
> +            --package-branch pyop2 emmarothwell1/restricted_function_space_review \
```suggestion
```

2024-04-26 21:43 UTC, merged