Docs for `variant="spectral"` on simplices
firedrakeproject/firedrake pull request #3221
Opened 2023-11-10 11:25 UTC by pbrubeck

# Description
These have to go together with https://github.com/firedrakeproject/tsfc/pull/301

2023-11-12 12:09 UTC, pbrubeck commented on docs/source/variational-problems.rst
> +.. _recursivenodes: https://pypi.org/project/recursivenodes/
```suggestion
.. _recursivenodes: https://tisaac.gitlab.io/recursivenodes/
```

2023-11-15 13:43 UTC, JDBetteridge requested changes
This is fine, but dependent on https://github.com/firedrakeproject/tsfc/pull/301

2023-11-17 10:20 UTC, connorjward reviewed
I would quite like to wait for the docs build to pass so we can review the artefact before merging. In any case there is little point in merging before then because no one will see the changes.

2023-11-23 11:10 UTC, connorjward approved these changes
I've checked the build artefact and this is good. Thanks!

2023-11-23 11:10 UTC, merged