MacOS install Xcode 15 fails
firedrakeproject/firedrake pull request #3249
Opened 2023-11-21 15:58 UTC by Ig-dolci

Some MacOS users are encountering fails to install Firedrake with Xcode15. Apparently, Xcode 15 beta has sorted it. Should be this informed in an install note?

2023-11-21 16:08 UTC, JDBetteridge requested changes
Maybe this could be added to the flowchart? https://www.firedrakeproject.org/download.html#debugging-install-problems. 

At the very least it should be moved down from the top section to debugging install problems section. We should bring this up at the meeting to try and find out how widespread this issue really is...

2023-11-21 16:21 UTC, Ig-dolci commented
> Maybe this could be added to the flowchart? https://www.firedrakeproject.org/download.html#debugging-install-problems.
> 
> At the very least it should be moved down from the top section to debugging install problems section. We should bring this up at the meeting to try and find out how widespread this issue really is...

Thank you, Jack. I will add this issue in the next meeting.

2023-11-22 16:58 UTC, dham commented on docs/source/download.rst
> +  install issue.
please tell them how.

2023-11-23 09:48 UTC, Ig-dolci commented on docs/source/download.rst
> +  install issue.
Done.

2023-11-23 11:27 UTC, JDBetteridge commented
Can we have a bit of a tidy up of various MacOS related fixes on the wiki, rather than just linking to another random page?

https://github.com/firedrakeproject/firedrake/wiki/Fixing-venv-on-macOS-after-homebrew-patches-Python
https://github.com/firedrakeproject/firedrake/wiki/Installing-pyenv
https://github.com/firedrakeproject/firedrake/wiki/macOS-version-support
and now
https://github.com/firedrakeproject/firedrake/wiki/Installation-Issues-with-Firedrake-on-Xcode-15-for-MacOS-Users

All contain various miscellaneous fixes related to MacOS. We should determine which advice is still relevant, consolidate this into one page and then add a link to the wiki sidebar and then link to that document from the Firedrake website.

2023-11-23 11:28 UTC, connorjward requested changes

2023-11-23 11:28 UTC, connorjward commented on docs/source/download.rst
> +  The instructions for the Xcode 15 update are available on this link `link
```suggestion
  The instructions for the Xcode 15 update are available on this `link 
```

2023-11-23 11:28 UTC, connorjward commented on docs/source/download.rst
> +  <https://github.com/firedrakeproject/firedrake/wiki/Installation-Issues-with-Firedrake-on-Xcode-15-for-MacOS-Users>`_
```suggestion
  <https://github.com/firedrakeproject/firedrake/wiki/Installation-Issues-with-Firedrake-on-Xcode-15-for-MacOS-Users>`_.
```

2023-11-23 11:28 UTC, connorjward commented on docs/source/download.rst
> +  The instructions for the Xcode 15 update are available on this link `link
says "link" twice.

2023-11-23 14:38 UTC, Ig-dolci commented
> Can we have a bit of a tidy up of various MacOS related fixes on the wiki, rather than just linking to another random page?
> 
> https://github.com/firedrakeproject/firedrake/wiki/Fixing-venv-on-macOS-after-homebrew-patches-Python https://github.com/firedrakeproject/firedrake/wiki/Installing-pyenv https://github.com/firedrakeproject/firedrake/wiki/macOS-version-support and now https://github.com/firedrakeproject/firedrake/wiki/Installation-Issues-with-Firedrake-on-Xcode-15-for-MacOS-Users
> 
> All contain various miscellaneous fixes related to MacOS. We should determine which advice is still relevant, consolidate this into one page and then add a link to the wiki sidebar and then link to that document from the Firedrake website.

Yes. I agree that we should organise these instructions.
I think that the instruction https://github.com/firedrakeproject/firedrake/wiki/Fixing-venv-on-macOS-after-homebrew-patches-Python can be removed. I just created a [wiki page](https://github.com/firedrakeproject/firedrake/wiki) `MacOS firedrake install`.

2023-11-23 17:42 UTC, connorjward commented
I think that rather than having an "everything MacOS" page we should have an FAQ style wiki document on "Fixing install issues" that we can link to from the website. We should split it into "Current" and "Archived" sections or similar.

2023-11-23 17:43 UTC, connorjward commented
Also https://github.com/firedrakeproject/firedrake/wiki/macOS-version-support should be kept in the policies and procedures section of the wiki.

2023-11-23 17:48 UTC, JDBetteridge commented
Sure, although mention of the mystery `MACOSX_DEPLOYMENT_TARGET` environment variable should be mentioned on the MacOS help page.

2023-12-06 16:57 UTC, closed without merging