Expunge Coefficient.ufl_domain
firedrakeproject/firedrake pull request #3259
Opened 2023-11-23 09:40 UTC by pbrubeck

# Description
This was still triggering warnings at interpolation (and when trying to output non-Lagrange functions). The if statement is there because we cannot call `extract_unique_domain` on a FunctionSpace.

2023-11-23 11:13 UTC, connorjward submitted a review, later dismissed
Looks sensible.

2023-11-23 11:48 UTC, JDBetteridge commented
Hurrah, now we are only raising <checks notes> 13414 warnings on CI!

This _is a massive improvement_ over the 20947 warnings we generated previously.

@pbrubeck do you fancy opening a similar PR to expunge this warning from UFL itself?

2023-11-23 13:48 UTC, pbrubeck commented
> Hurrah, now we are only raising 13414 warnings on CI!
> 
> This _is a massive improvement_ over the 20947 warnings we generated previously.
> 
> @pbrubeck do you fancy opening a similar PR to expunge this warning from UFL itself?

I am not entirely sure we are completely eliminating this warnigns. Maybe I'll first open a ufl PR that fails instead of raising the warning to detect where else we need to change our code, and then open another PR to remove the warning.

2023-11-23 17:59 UTC, wence- commented
> > Hurrah, now we are only raising 13414 warnings on CI!
> > This _is a massive improvement_ over the 20947 warnings we generated previously.
> > @pbrubeck do you fancy opening a similar PR to expunge this warning from UFL itself?
> 
> I am not entirely sure we are completely eliminating these warnigns. Maybe I'll first open a ufl PR that fails instead of raising the warning to detect where else we need to change our code, and then open another PR to remove the warning.

you can either turn warnings into errors in pytest, or, if you run just a python script, do `python -Werror --pdb script.py` to turn warnings into errors and drop into the debugger: https://docs.python.org/3/using/cmdline.html#cmdoption-W

2023-11-23 20:52 UTC, pbrubeck commented on .github/workflows/build.yml
> +            --package-branch tsfc pbrubeck/expunge-ufl-domain \
```suggestion
```

2023-11-23 20:57 UTC, pbrubeck commented
We went down to 1249 warnings after making sure this issue is never triggered by the tests.

2023-11-24 09:37 UTC, connorjward submitted a review, later dismissed
Thanks for taking the time to do this.

2023-11-27 11:14 UTC, connorjward requested changes
Just clearing up a strange bit of code. Otherwise fine.

2023-11-27 11:14 UTC, connorjward commented on firedrake/preconditioners/patch.py
> +        V, _ = map(operator.methodcaller("function_space"), J.arguments())
```suggestion
        V = J.arguments()[0].function_space()
```

2023-11-29 16:24 UTC, dham submitted a review, later dismissed

2023-11-29 16:31 UTC, ReubenHill approved these changes

2023-11-29 17:28 UTC, merged