Add optional variant kwarg to FunctionSpace()
firedrakeproject/firedrake pull request #3295
Opened 2023-12-16 21:17 UTC by pbrubeck

# Description

2023-12-20 04:48 UTC, rckirby requested changes
This is about what I had in mind.   I checked out the branch and it did what I expected for Lagrange and Raviart-Thomas.

I'd like to see some tests exercising the feature.  It might be sufficient to grep for places where `variant` is passed into a `FiniteElement` and then into a `FunctionSpace` and use this shortcut and make sure that the test suite still passes?

2024-02-19 15:28 UTC, pbrubeck commented on tests/regression/test_function_spaces.py
> +    "FunctionSpaces defined with different element families differ."
```suggestion
    "FunctionSpaces defined with different element variants differ."
```

2024-02-19 17:00 UTC, rckirby approved these changes

2024-02-21 16:37 UTC, dham approved these changes

2024-02-21 16:37 UTC, merged