Make VTK optional
firedrakeproject/firedrake pull request #3324
Opened 2024-01-12 19:10 UTC by JDBetteridge

# Description
Recent issues on ARM based Mac + the long standing issue where we have to distribute VTK wheels prompted making VTK an optional dependency.

2024-01-12 20:10 UTC, colinjcotter commented
Are you still going to distribute the wheels?

2024-01-12 20:31 UTC, JDBetteridge commented
Probably, although VTK are getting better at releasing up to date wheels: https://pypi.org/project/vtk/#history

2024-01-15 11:22 UTC, connorjward requested changes

2024-01-15 11:22 UTC, connorjward commented on firedrake/output/paraview_reordering.py
> +        "pip install vtk"
Is this going to be robust enough? What is VTK's release schedule like?

2024-01-15 11:22 UTC, connorjward commented on firedrake/output/paraview_reordering.py
> +        "Error importing vtkmodules, you may need to install by executing\n\t"
I feel like we could give the user a slightly better message. Something like:

"Cannot import vtkmodules. Firedrake does not install VTK by default so you may need to install it by running pip install vtk first."

I feel that the current message doesn't sound deliberate enough.

2024-01-15 11:24 UTC, connorjward commented on firedrake/output/paraview_reordering.py
> +        "pip install vtk"
I've just checked the link you shared above. I'm convinced. They seem to be releasing wheels every month or so and are supporting the latest Pythons.

2024-01-15 14:28 UTC, connorjward reviewed
I am happy with this. @JDBetteridge believes that some bikeshedding/further API thought is required before merging.

2024-01-17 16:15 UTC, dham submitted a review, later dismissed
Please make vtk default on.

2024-03-05 15:26 UTC, JDBetteridge commented
I think this is ready, I think I want to kick the "move `checkpointing.py` into the `output` directory" can down the road.

2024-03-05 15:31 UTC, connorjward approved these changes

2024-03-06 16:31 UTC, dham approved these changes

2024-03-06 16:31 UTC, merged