Fix constant array dimension error.
firedrakeproject/firedrake pull request #3344
Opened 2024-01-22 14:05 UTC by Ig-dolci

# Description
Fix constant array dimension error.

2024-01-22 14:06 UTC, Ig-dolci commented on firedrake/adjoint_utils/constant.py
> +        return numpy.prod(self.dat.data_ro.ndim)
@JDBetteridge  is it `self.dat.data_ro.ndim` here?

2024-01-22 15:16 UTC, JDBetteridge requested changes
30% sure...

2024-01-22 15:16 UTC, JDBetteridge commented on firedrake/adjoint_utils/constant.py
> +        return numpy.prod(self.dat.data_ro.ndim)
```suggestion
        return self.dat.cdim
```

2024-01-22 17:00 UTC, connorjward reviewed
Could we get a simple test of this? Even just a test which is "this code should not raise an exception" might be suitable.
Then discussions of "I think this is the right thing to do" can be validated.

2024-01-24 16:48 UTC, dham approved these changes

2024-01-24 16:49 UTC, merged