External operators
firedrakeproject/firedrake pull request #3394
Opened 2024-02-07 15:30 UTC by nbouziani

This PR contains the Firedrake implementation of external operators. The corresponding UFL implementation was merged in https://github.com/FEniCS/ufl/pull/206. The Firedrake infrastructure to make external operators has already been introduced in #2297, making that PR pretty "small".

The external operator interface allows for incorporating arbitrary operators mapping between finite element spaces in Firedrake. Those operators are external in the sense that their implementation is left to be specified by the user. This PR mainly contains:

- The assembly mechanism required for evaluating external operators, and expressions/variational forms containing external operators.
- The abstract external operator class that orchestrates the assembly
- The ML operator which allows for incorporating machine learning models implemented in PyTorch in Firedrake
- A new manual chapter and, hopefully, one or two demos/tutorials to come up soon

2024-02-07 15:31 UTC, nbouziani commented
Docstrings and manual to be updated/completed soon.

2024-02-07 16:20 UTC, nbouziani commented on firedrake/external_operators/ml_operator.py
> +
```suggestion
```

2024-02-07 16:55 UTC, dham requested changes

2024-02-07 16:55 UTC, dham commented on firedrake/external_operators/abstract_external_operators.py
> +class RegisteringAssemblyMethods(UFLType):
AssemblyRegisterMetaClass

2024-02-07 16:55 UTC, dham commented on firedrake/external_operators/abstract_external_operators.py
> +class RegisteringAssemblyMethods(UFLType):
Please document this dark magic.

2024-02-07 16:55 UTC, dham commented on firedrake/external_operators/abstract_external_operators.py
> +        Here are examples on how to specify the implementation of:
Lift to manual

2024-02-07 16:55 UTC, dham commented on firedrake/external_operators/ml_operator.py
> +        J = self._jac()
pytorch?

2024-02-07 16:55 UTC, dham commented on firedrake/external_operators/point_expr_operator.py
> +        """
Numpydoc

2024-02-07 16:55 UTC, dham commented on firedrake/ml/pytorch/neural_network_operators.py
> +        δy_P = self._pre_forward_callback(δy)
Don't use greek!!!!!!!

2024-02-21 16:21 UTC, dham approved these changes

2024-02-21 16:23 UTC, merged