Added in a RestrictedFunctionSpace class
firedrakeproject/firedrake pull request #3426
Opened 2024-02-26 15:51 UTC by emmarothwell1

# Description
Add in a RestrictedFunctionSpace class.

This marks boundary nodes in the definition of the FunctionSpace with the goal of removing them from calculations such as in assembly. 
This currently only works for FunctionSpace objects, restricted mixed spaces and restrictions based on already defined RestrictedFunctionSpaces are still being worked on elsewhere. 
There are tests in tests/regression/test_restricted_function_space.py to check assembly and solve works. 
There is also a linked PyOP2 pull request at:

2024-02-28 17:09 UTC, dham requested changes
This is very close. Just a few minor issues.

2024-02-28 17:09 UTC, dham commented on firedrake/cython/dmcommon.pyx
> +                            if boundary_set and PetscBTLookup(seen_boundary, p) and l <= 1:
please don't use the variable name `l`. It's super confusing.

2024-03-01 23:37 UTC, ksagiyam commented
This PR https://github.com/firedrakeproject/firedrake/pull/3288 has just been merged. Rebasing will cause conflicts in `assemble.py`, so I suggest that you focus on fixing the boundary condition issue first. Once you resolve the BC issue, I can do rebasing.

2024-04-04 13:23 UTC, ksagiyam commented
It seems the big change in assemble.py has successfully been merged into this branch. The PR on halo_exchange_sf was merged yesterday, so you can drop the commit you cherry picked, and merge `master`.

2024-04-22 21:28 UTC, closed without merging

2024-04-22 21:28 UTC, ksagiyam commented
Superseded https://github.com/firedrakeproject/firedrake/pull/3215.