Ensemble reduced functional
firedrakeproject/firedrake pull request #3500
Opened 2024-04-12 11:27 UTC by Ig-dolci

2024-04-17 09:13 UTC, Ig-dolci commented on firedrake/adjoint/ensemble_reduced_functional.py
> +
Add the math of ensemble reduced functional to make clear what is going on.

2024-04-17 09:15 UTC, Ig-dolci commented on firedrake/adjoint/ensemble_reduced_functional.py
> +    def derivative(self, adj_input=1.0, options=None, op=MPI.SUM):
remove `op=MPI.SUM`

2024-04-17 09:25 UTC, Ig-dolci commented on firedrake/adjoint/ensemble_reduced_functional.py
> +
We should document that J is defined over a `self.ensemble.comm`.

2024-04-17 09:29 UTC, Ig-dolci commented on firedrake/adjoint/ensemble_reduced_functional.py
> +    `documentation <https://www.firedrakeproject.org/parallelism.html#id8>`_.
`Firedrake manual <https://www.firedrakeproject.org/parallelism.html#id8>`_.

2024-04-17 09:32 UTC, Ig-dolci commented on firedrake/adjoint/ensemble_reduced_functional.py
> +            total_functional = firedrake.Function(local_functional.function_space())
```suggestion
            total_functional = type(local_functional)(local_functional.function_space())
```

2024-04-17 09:37 UTC, Ig-dolci commented on firedrake/adjoint/ensemble_reduced_functional.py
> +                dJdm_total.append(
See `Enlist` in pyadjoint and improve this code.

2024-04-17 09:42 UTC, Ig-dolci commented on firedrake/adjoint/ensemble_reduced_functional.py
> +        else:
Add the case where the local derivative can be a float.

2024-05-01 15:20 UTC, dham submitted a review, later dismissed

2024-05-01 15:20 UTC, dham commented on firedrake/adjoint/ensemble_reduced_functional.py
> +    `self.ensemble.comm` communicator. To understand more about how ensemble parallelism
```suggestion
    `ensemble.comm` communicator. To understand more about how ensemble parallelism
```

2024-05-01 15:20 UTC, dham commented on firedrake/adjoint/ensemble_reduced_functional.py
> +            The employed MPI operation for the `Ensemble.allreduce` the derivatives.
```suggestion
```

2024-05-01 15:20 UTC, dham commented on firedrake/adjoint/ensemble_reduced_functional.py
> +            The result of Allreduce operations of ``dJdm_local`` into ``dJdm_total`` over the`Ensemble.ensemble_comm`.
should be overloaded type rather than Function.

2024-05-01 21:10 UTC, colinjcotter commented
This looks interesting. What’s the motivating application for it?

2024-05-02 07:46 UTC, Ig-dolci commented
> This looks interesting. What’s the motivating application for it?

Ensemble functional will be helpful when your cost function `J` is a sum of multiple functionals `J_i`, with each `J_i`  requiring the computation of an adjoint-based gradient. That is typically seen in full waveform inversion, a technique used to create subsurface imaging.

2024-05-02 08:36 UTC, connorjward requested changes
I think the tests should run on more ranks to stress the spatial parallelism. Otherwise very happy to approve.

2024-05-02 08:58 UTC, connorjward approved these changes

2024-05-02 16:51 UTC, merged