Constant
firedrakeproject/firedrake pull request #3525
Opened 2024-04-25 10:08 UTC by JDBetteridge

2024-04-25 11:04 UTC, JDBetteridge commented on tests/regression/test_constant.py
> +#pytest.skip(allow_module_level=True, reason="pyop3 TODO")
```suggestion
```

2024-04-25 14:03 UTC, connorjward requested changes

2024-04-25 14:03 UTC, connorjward commented on firedrake/constant.py
> +                raise DataValueError("Cannot assign to constant, value has incorrect shape")
```suggestion
        if self.ufl_shape() and np.array(value).shape != self.ufl_shape():
            raise DataValueError("Cannot assign to constant, value has incorrect shape")
```

2024-04-26 09:34 UTC, connorjward commented
I think this is superseded by #3527

2024-04-26 09:34 UTC, closed without merging