Incorperate TinyASM into Firedrake
firedrakeproject/firedrake pull request #3604
Opened 2024-05-31 17:13 UTC by JDBetteridge

# Description
Move TinyASM into Firedrake. Later job is to rewrite in C, but for now keep as C++ and use pybind11.

`python -c "import tinyasm"` segfaults, but this happened before :slightly_frowning_face:

2024-06-04 10:00 UTC, JHopeCollins requested changes

2024-06-04 10:00 UTC, JHopeCollins commented on tinyasm/matinvert.cpp
> +using namespace std;
```suggestion
```

2024-06-04 10:00 UTC, JHopeCollins commented on tinyasm/tinyasm.cpp
> +#include <iostream>
```suggestion
```

2024-06-04 10:00 UTC, JHopeCollins commented on tinyasm/tinyasm.cpp
> +#include <chrono>
```suggestion
```

2024-06-04 10:00 UTC, JHopeCollins commented on tinyasm/tinyasm.cpp
> +            }
```suggestion
```

2024-06-04 10:44 UTC, wence- commented
TODO (perhaps)? Ask @florianwechsung what license is appropriate. I made some non-substantive changes that I am happy to license under whatever.

2024-06-05 15:14 UTC, dham commented
Good catch Lawrence. We need to ask Florian for a licence. LGPL would match the rest of Firedrake. MIT would also be fine.

2024-06-05 22:04 UTC, florianwechsung commented
Happy to see TinyASM being moved into firedrake! LGPL is good with me.

2024-06-07 12:11 UTC, JHopeCollins approved these changes
Firedrake is under LGPL so no extra license needed.

2024-06-19 15:34 UTC, dham approved these changes

2024-06-19 15:34 UTC, merged