Ksagiyam/add periodic hex mesh
firedrakeproject/firedrake pull request #3667
Opened 2024-07-05 16:12 UTC by ksagiyam

2024-12-18 13:31 UTC, juliusgh commented
Hi @ksagiyam, great that you are working on this!

I was just looking for this feature and saw your PR. In the meantime, the corresponding PETsc PR https://gitlab.com/petsc/petsc/-/merge_requests/7677 has been merged.

Do you know what is missing in your PR and do you intend to continue working on it? Otherwise, I could also take a look.

2024-12-18 13:36 UTC, ksagiyam commented
I need to make this branch up-to-date. I also noticed that I had not labeled boundaries correctly, so I need to fix that. I will work on this later today.

2024-12-19 16:01 UTC, ksagiyam commented on firedrake/utility_meshes.py
> +        Directions of periodicity; if `None`, the mesh is made periodic in all directions.
Yes. Fixed.

2024-12-19 16:19 UTC, ksagiyam commented on firedrake/utility_meshes.py
> +            reorder=reorder_noop,
We only need correct reordering and distribution for the mesh returned by `_postprocess_periodic_mesh()`, so we just avoid unnecessary reordering and adding overlap when making this intermediate mesh `m`.

2024-12-19 16:31 UTC, ksagiyam commented on firedrake/utility_meshes.py
> +        return _postprocess_periodic_mesh(new_coordinates,
We call `_postprocess_periodic_mesh()` to make DMPlex DG coordinates from Firedrake DG coordinates. For periodic hex mesh, `createBoxMesh()` directly makes DMPlex DG coordinates (and we later convert these to Firedrake DG coordinates), so we do not need this additional step.

2024-12-19 16:42 UTC, connorjward commented on firedrake/utility_meshes.py
> +        return _postprocess_periodic_mesh(new_coordinates,
Got it. Thanks

2024-12-19 16:47 UTC, connorjward requested changes
One trivial thing. With that please consider this as approved by me.

2024-12-19 16:47 UTC, connorjward commented on firedrake/utility_meshes.py
> +        plex = PETSc.DMPlex().createBoxMesh((nx, ny, nz), lower=(0., 0., 0.), upper=(Lx, Ly, Lz), simplex=False, periodic=directions, interpolate=True, sparseLocalize=False, comm=comm)
```suggestion
        plex = PETSc.DMPlex().createBoxMesh(
            (nx, ny, nz),
            lower=(0., 0., 0.),
            upper=(Lx, Ly, Lz),
            simplex=False,
            periodic=directions,
            interpolate=True,
            sparseLocalize=False,
            comm=comm,
        )
```

2024-12-19 22:05 UTC, merged

2024-12-19 22:05 UTC, ksagiyam commented
Thanks, Connor.