PC: Housekeeping
firedrakeproject/firedrake pull request #3736
Opened 2024-08-14 16:59 UTC by pbrubeck

# Description

`PCSNESBase` implements `get_form()`

`FacetSplitPC` now supports a split on to any number of restricted elements (this allows proper subspaces).

`HiptmairPC` now supports restricted potential spaces.

`tabulate_exterior_derivative` works for simplices.

2024-10-02 15:47 UTC, dham requested changes

2024-10-02 15:47 UTC, dham commented on firedrake/preconditioners/assembled.py
> +        if P.getType() == "python":
please stop programming in Java.

2024-10-02 15:47 UTC, dham commented on firedrake/preconditioners/base.py
> +        and `bcs` is a list of `DirichletBC` boundary conditions (possibly `None`).
Numpydoc style docstring.

2024-10-02 15:47 UTC, dham commented on firedrake/preconditioners/facet_split.py
> +        assert len(V) == 1, "Decomposition of mixed elements is not supported"
please to be exception.

2024-10-02 15:47 UTC, dham commented on firedrake/preconditioners/facet_split.py
>              self._global_iperm = PETSc.IS().createGeneral(global_indices, comm=P.getComm())
use `self.comm`?

2024-10-02 15:48 UTC, JDBetteridge commented on firedrake/preconditioners/base.py
> +        and `bcs` is a list of `DirichletBC` boundary conditions (possibly `None`).
https://github.com/firedrakeproject/firedrake/wiki/Docstrings

2024-10-09 15:55 UTC, dham approved these changes

2024-10-09 15:55 UTC, merged