Add JAX coupling
firedrakeproject/firedrake pull request #3759
Opened 2024-09-09 23:55 UTC by nbouziani

This PR adds support to couple JAX and Firedrake in a differentiable fashion. It extends the previous work on coupling Firedrake and PyTorch (cf. #3394 and #2804) to support the JAX framework as well as downstream libraries. It allows to embed JAX model into Firedrake, thanks to the `MLOperator` external operator class, and to embed Firedrake system into JAX. These new capabilities can be obtained by importing from the `firedrake.ml.jax` module. It also adds options to install JAX on the fly when installing Firedrake. Main additions:

- Add a JAX custom operator (`FiredrakeJaxOperator`) to represent Firedrake operators expressed as a ReducedFunctional, wherein forward and backward computations are delegated to the reduced functional.
- Add a new ml operator (`JaxOperator`) to represent JAX operations embedded in Firedrake
- Add support for installing JAX
- Add mapping operator from JAX to Firedrake, and vice-versa
- Some tests

2024-09-09 23:56 UTC, nbouziani commented on firedrake/ml/jax/fem_operator.py
> +    # Citations().register(TODO)
This will come shortly.

2024-09-10 15:20 UTC, nbouziani commented on firedrake/ml/jax/fem_operator.py
> +    return partial(FiredrakeJaxOperator.forward, jax_op)
Add a comment to explain why this workaround exists

2024-09-11 15:10 UTC, JDBetteridge requested changes
Please use type hinting as per the "new" policy:
https://github.com/firedrakeproject/firedrake/wiki/Docstrings

2024-09-12 11:18 UTC, JDBetteridge approved these changes
Docstrings and function signatures have been updated to use type hinting.

2024-09-12 11:18 UTC, merged