Unpin mpi4py version
firedrakeproject/firedrake pull request #3777
Opened 2024-09-23 09:30 UTC by JDBetteridge

# Description

2024-09-23 12:44 UTC, JDBetteridge commented on .github/workflows/build.yml
> +            --package-branch slepc JDBetteridge/merge_upstream \
```suggestion
            --package-branch slepc JDBetteridge/merge-upstream \
```

2024-09-24 15:22 UTC, JDBetteridge commented on .github/workflows/build.yml
> +            --package-branch petsc JDBetteridge/merge_upstream \
```suggestion
            --package-branch petsc JDBetteridge/fix_mpi4_build \
```

2024-10-02 15:17 UTC, dham requested changes
Looks good except that we should enable a `--mpi4py-version=3.1.6` option to the install script and have it honour that on lines 1859 and 2004 so that we can bail out users of older OSes who need to install with mpi4py v3

2024-10-05 13:35 UTC, JHopeCollins commented on scripts/firedrake-install
> +    parser.add_argument("--mpi4py-version", help="Specify an exact version of mpi4py to install")
Did you mean to add this argument twice?

2024-10-09 15:58 UTC, merged