Dolci/exchange fwi demo test
firedrakeproject/firedrake pull request #3836
Opened 2024-10-24 12:56 UTC by Ig-dolci

# Description

This PR removes the full waveform inversion (FWI) demos from the test suite and introduces a simplified version of the test within `test/regression`.

2024-10-30 16:36 UTC, dham requested changes
This deals with the proximate problem but violates single source of truth. We need to put a mode into the demo that makes it faster (possibly by branching on an environment variable).

2024-11-06 16:48 UTC, dham requested changes

2024-11-06 16:48 UTC, dham commented on demos/full_waveform_inversion/full_waveform_inversion.py.rst
> +        if test:
```suggestion

    def spatial_time_parameters():
        import os
        if os.getenv("FIREDRAKE_CI_TESTS") == "1":
```

2024-11-06 16:48 UTC, dham commented on demos/full_waveform_inversion/full_waveform_inversion.py.rst
> +    dt, final_time, nx, ny = spatial_time_parameters(test)
```suggestion
    dt, final_time, nx, ny = spatial_time_parameters()
```

2024-11-07 11:33 UTC, Ig-dolci commented on demos/full_waveform_inversion/full_waveform_inversion.py.rst
> +        if test:
done.

2024-11-07 11:37 UTC, connorjward submitted a review, later dismissed
Thanks!

2024-11-07 16:24 UTC, connorjward approved these changes

2024-11-07 16:24 UTC, merged