`u.sub(0)` should still be in a `ComponentFunctionSpace` if the vector is 1 dimensional
firedrakeproject/firedrake pull request #3902
Opened 2024-12-03 12:08 UTC by JHopeCollins

Currrently, for `u` in a `VectorFunctionSpace`, the `Functions` returned by `u.sub` are in different types of spaces depending on the dimension of the VFS.

- if `dim` is 2 or higher, then `u.sub(i).function_space()` is a `ComponentProxyFunctionSpace`.
- if `dim` is 1, then `u.sub(0) is u`, instead of being in the `ComponentProxyFunctionSpace`.

This PR changes the `u.sub(0)` for 1-dim vectors to be in the `ComponentProxyFunctionSpace` by changing the if-statement to test `self.rank` instead of `self.dof_dset.cdim`.

2024-12-03 15:10 UTC, connorjward requested changes
Basically just f-strings

2024-12-03 15:10 UTC, connorjward commented on firedrake/function.py
> +            raise IndexError("Invalid component %d, not in [0, %d)" % (i, bound))
```suggestion
            raise IndexError(f"Invalid component {i}, not in [0, {bound})")
```

2024-12-03 15:10 UTC, connorjward commented on firedrake/function.py
> +                                                     name="view[%d](%s)" % (0, self.name())),))
```suggestion
                return (CoordinatelessFunction(self.function_space().sub(0), val=self.dat,
                                               name=f"view[0]({self.name()})"),)
```

2024-12-03 15:10 UTC, connorjward commented on firedrake/function.py
> +                                                    name="view[%d](%s)" % (i, self.name()))
```suggestion
                                                    name=f"view[{i}]({self.name()})")
```

2024-12-03 15:10 UTC, connorjward commented on firedrake/function.py
> +            raise IndexError("Invalid component %d, not in [0, %d)" % (i, bound))
```suggestion
            raise IndexError(f"Invalid component {i}, not in [0, {bound})")
```

2024-12-03 15:10 UTC, connorjward commented on firedrake/functionspaceimpl.py
>              raise IndexError("Invalid component %d, not in [0, %d)" % (i, bound))
```suggestion
            raise IndexError(f"Invalid component {i}, not in [0, {bound})")
```

2024-12-03 15:10 UTC, connorjward commented on firedrake/functionspaceimpl.py
> +        return tuple((self, ))
```suggestion
        return (self, )
```
`tuple` not needed.

2024-12-03 15:10 UTC, connorjward commented on firedrake/functionspaceimpl.py
> +            raise IndexError("Invalid component %d, not in [0, %d)" % (i, bound))
```suggestion
            raise IndexError(f"Invalid component {i}, not in [0, {bound})")
```

2024-12-03 16:21 UTC, connorjward approved these changes

2024-12-03 17:05 UTC, merged

2024-12-04 14:17 UTC, pbrubeck commented on firedrake/function.py
> +            return tuple((self, ))
`tuple` is not needed here

2024-12-04 14:18 UTC, pbrubeck commented on firedrake/function.py
> +            return tuple((self, ))
Same here