DO NOT MERGE
firedrakeproject/firedrake pull request #3947
Opened 2024-12-30 04:03 UTC by pbrubeck

# Description

2025-01-08 15:04 UTC, ksagiyam commented on firedrake/formmanipulation.py
> +        # TODO find a way to distinguish empty Forms avoiding expand_derivatives
I am not sure if there is a robust solution for this. `expand_derivatives()` might be expensive for large forms. Can we not handle zero form after calling tsfc_compile_form()? Do we do this here for Slate?

2025-01-08 15:26 UTC, pbrubeck commented on firedrake/adjoint_utils/variational_solver.py
> +                    self._ad_adj_F = adjoint(dFdu, derivatives_expanded=True)
The one checking that we indeed have a bilinear form (the only `ValueError` in `firedrake.adjoint`) https://github.com/firedrakeproject/firedrake/blob/2a0c03b244ef9f641fe959d026225d49dd007a14/firedrake/ufl_expr.py#L334
There is a similiar one in `ufl.adjoint`
https://github.com/firedrakeproject/ufl/blob/bfa596dd3f0e121168305451badf6b24c98dd7f6/ufl/adjoint.py#L72

2025-01-08 15:26 UTC, pbrubeck commented on firedrake/formmanipulation.py
> +        # TODO find a way to distinguish empty Forms avoiding expand_derivatives
That's why I put the comment there. But both `action` and `adjoint` call `expand_derivatives` by default. Maybe this is a new behaivour that was intruduced alongside BaseForm. If `expand_derivatives` were not called, Fieldsplit/SLATE/EquationBC would not reach the empty Forms.

2025-01-08 15:26 UTC, pbrubeck commented on firedrake/formmanipulation.py
> +        # TODO find a way to distinguish empty Forms avoiding expand_derivatives
https://github.com/firedrakeproject/ufl/blob/bfa596dd3f0e121168305451badf6b24c98dd7f6/ufl/formoperators.py#L174

2025-01-08 15:45 UTC, ksagiyam commented on firedrake/formmanipulation.py
> +        # TODO find a way to distinguish empty Forms avoiding expand_derivatives
I see. I think I am fine with this.

2025-01-09 10:51 UTC, JHopeCollins commented on firedrake/formmanipulation.py
> +            W = DualSpace(W.mesh(), W.ufl_element())
Can you use the `subspace` function here too? It will need a switch adding for primal/dual but I think it would be nicer to use `subspace` for both.

I think it would also be nice to lift `subspace` out, possibly into one of the functionspace files. It's useful more generally - see for example line 678 in `slate.py` where we have the same if/else block to construct the subspace.

2025-01-09 10:59 UTC, pbrubeck commented on firedrake/formmanipulation.py
> +            W = DualSpace(W.mesh(), W.ufl_element())
I was thinking to extend `FunctionSpace.__getitem__` to allow a list index return the subspace, since this is how sub-arrays are extracted in numpy.

2025-01-09 11:04 UTC, JHopeCollins commented on firedrake/slate/slate.py
>              nargs.append(Argument(W, arg.number(), part=arg.part()))
Using `subspace` this whole function could just be be replaced with
```suggestion
         return (Argument(subspace(V, self._blocks[i]), arg.number(), part=arg.part())
                 for i, arg in enumerate(self.operands[0].arguments()))
```

2025-01-09 11:12 UTC, JHopeCollins commented on firedrake/formmanipulation.py
> +            W = DualSpace(W.mesh(), W.ufl_element())
I was actually thinking exactly the same thing the other day.

It would be great to have it for `Function` too so that you can get a `Mixed` subfunction viewing the relevant subcomponents. `ExtractSubBlock.cofunction` would then basically just be calling `cofunction[idxs]`.
There are definitely other places where that would be useful too, for example in the `EnsembleFunction` I've been working on [here](https://github.com/firedrakeproject/firedrake/blob/dfe98bf906b0c063822abec533fccc1d3bea67f3/firedrake/ensemblefunction.py#L59).

What does `FunctionSpace.collapse()` do? It just looks like it would return a copy of the `FunctionSpace`.

2025-01-09 11:13 UTC, pbrubeck commented on firedrake/formmanipulation.py
> +            W = DualSpace(W.mesh(), W.ufl_element())
@ksagiyam what do you think about this __getitem__ idea? Currenty, indexing by a scalar returns `IndexedProxyFunctionSpace`, but indexing by a list of a single item would return the collapsed version of this space.

2025-01-09 11:49 UTC, connorjward commented on firedrake/formmanipulation.py
> +            W = DualSpace(W.mesh(), W.ufl_element())
`__getitem__` for `Function` is implemented in UFL so the changes would be needed there I think.

2025-01-09 11:54 UTC, pbrubeck commented on firedrake/formmanipulation.py
> +            W = DualSpace(W.mesh(), W.ufl_element())
I'm not to worried for the `Function` case, that one seems more involved, as they are Expressions in the UFL sense, and extracting a component naturally means a scalar compoment, but here it seems that we want a MixedFunctionSpace (possibly vector-valued) component.

2025-01-09 11:58 UTC, JHopeCollins commented on firedrake/formmanipulation.py
> +            W = DualSpace(W.mesh(), W.ufl_element())
It could also be added to `sub` or `subfunctions`, although they both also have issues.
`sub` explicitly says it is for bcs, and `subfunctions` is already a tuple not a method so it would probably have to become a local class with `__getitem__` overridden so we could deal with single or multiple indices.

2025-01-09 12:35 UTC, ksagiyam commented on firedrake/formmanipulation.py
> +            W = DualSpace(W.mesh(), W.ufl_element())
That sounds slightly odd to me. Can you instead rewrite `collapse()` so that it would take a list of indices as an optional argument?

@JHopeCollins `collapse()` basically forgets parents. They do something nontrivial in ProxyFunctionSpace and in MixedFunctionSpace.

2025-01-09 13:02 UTC, JHopeCollins commented on firedrake/formmanipulation.py
> +            W = DualSpace(W.mesh(), W.ufl_element())
Ok thanks.

It does strip the parent information, I don't think the name `collapse` would be where I would look for this functionality - it would be more intuitive in subfunctions or sub.

2025-01-09 14:50 UTC, JHopeCollins requested changes

2025-01-09 14:50 UTC, JHopeCollins commented on firedrake/functionspaceimpl.py
> +        if isinstance(i, list):
We should allow any iterable, not just a list.
```suggestion
        if not isinstance(i, int):
```

2025-01-09 14:57 UTC, JHopeCollins requested changes

2025-01-09 14:57 UTC, JHopeCollins commented on firedrake/functionspaceimpl.py
> +        from firedrake.functionspace import MixedFunctionSpace
I think we should cache the mixed subspaces like we do for the non-mixed subspaces. Otherwise we get a "different" space every time we call with the same indices.

2025-01-09 15:38 UTC, ksagiyam requested changes

2025-01-09 15:38 UTC, ksagiyam commented on firedrake/functionspaceimpl.py
> +
As I said elsewhere, I think this is odd. I feel we are abusing `__getitem__()`. If we want this feature, we should do it somewhere else (in a new method or in `collapse()`), not in `__getitem__()`.

2025-01-09 15:49 UTC, connorjward commented on firedrake/functionspaceimpl.py
> +        if isinstance(i, list):
I think the behaviour of `__getitem__` is a bit subtle here. Calling `obj[1, 2, 3]` is *exactly the same* as calling `obj[(1, 2, 3)]` which is not quite the same as `obj[[1, 2, 3]]`.

I think having something like `space[1, 2]` would suggest to someone that `space` is somehow nested, whereas `space[[1, 2]]` suggests a subset of the indices.

2025-01-09 19:26 UTC, pbrubeck commented on firedrake/functionspaceimpl.py
> +
I removed the call to collapse(), and will leave `V[(i,)] == V[i]`

2025-01-09 20:37 UTC, ksagiyam commented on firedrake/functionspaceimpl.py
> +
So now `V[(i,)]` is a non-collapsed indexed space and `V[(i, j)]` is a new collapsed mixed space?

2025-01-09 20:45 UTC, pbrubeck commented on firedrake/functionspaceimpl.py
> +
Not quite. `V[(i, )]` is no longer collapsed, which means that it is a `IndexedProxyFunctionSpace`. But collapsing a `MixedSpace` does nothing, as the new `MixedSpace` subspace has lost any reference to the parent `MixedSpace`. I only required collapsing the subspaces because Fieldsplit builds a new NLVP, and we cannot use proxy spaces for BCs.

2025-01-09 21:06 UTC, ksagiyam commented on firedrake/functionspaceimpl.py
> +
Please read my comment carefully. I understand why we need this, but I have been claiming that we should not have `__getitem__()` have multiple meanings depending on if we pass `int` or `tuple`/`list`. If the former returns something which remembers the parent and the latter returns something which does not, it indicates that this feature should be implemented somewhere else.

2025-01-10 10:29 UTC, JHopeCollins commented on firedrake/functionspaceimpl.py
> +
That's a good point, I hadn't quite appreciated whether the subspace remembers the parent or not. If I understand correctly then we currently have:

1. `subfunction` (and by extension `__getitem__`) returns a `FunctionSpace`/`Function` for a _single_ subcomponent that _remembers_ the parent.
2. `collapse` returns a `FunctionSpace`/`Function` with _all_ components that _forgets_ the parent.

What we want is a utility for returning a `FunctionSpace`/`Function` with _some_ subcomponents that _forgets_ the parent. The fact that it returns a subspace matches with `subfunction`, but the fact that it forgets the parent matches with `collapse`. This means that if we extend either of the existing methods then we will introduce some ambiguity into that method's purpose.

If we are to avoid this ambiguity then Koki is right, we need a new method given how important clarity is with symbolic information (e.g. the `split`->`subfunction` change).

This information should also be added to the docstrings for `subfunctions`/`sub`/`__getitem__`/`collapse`/the new method for all the `FunctionSpace` classes plus the `Function` classes and `Cofunction`.

2025-01-10 20:37 UTC, pbrubeck commented on firedrake/formmanipulation.py
> +            W = DualSpace(W.mesh(), W.ufl_element())
I'll go back to the old `subspace` method I had for splitting purposes

2025-01-10 20:38 UTC, pbrubeck commented on firedrake/functionspaceimpl.py
> +        if isinstance(i, list):
No longer relevant

2025-01-13 09:37 UTC, JHopeCollins commented on firedrake/functionspaceimpl.py
> +
I think for this PR just doing the `subspace` function is fine, it already improves the `formmanipulation` code nicely. Let's not hold up this PR any more.
We can discuss the best way forward for lifting `subspace` out separately.

2025-01-15 20:36 UTC, pbrubeck commented on .github/workflows/build.yml
> +            --package-branch ufl pbrubeck/merge-upstream \
```suggestion
```

2025-01-15 22:09 UTC, ksagiyam approved these changes

2025-01-15 22:09 UTC, merged